# Copyright (C) 2017 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU LGPL v2.1 or later

language: cpp
dist: xenial

arch:
  - ppc64le

script:
  - set -e
  - sudo apt-get install g++  
  - ./autogen.sh
  - configure_args=(
        CC=gcc
        CXX=g++

        --enable-doc
    )
    && ./configure "${configure_args[@]}"  # -Werror would fail configure checks!
  - make CXXFLAGS="${CXXFLAGS} -Werror" all
  - make CXXFLAGS="${CXXFLAGS} -Werror" check
  - ./test/mytest  # i.e. ensure that the example exits with code 0
  - ./test/mytest --compiler
  - ./test/mytest --html
  - ./test/mytest --text-terse
  - ./test/mytest --text-verbose
  - make distcheck  # without AddressSanitizer
  - ./check-abi.sh

addons:
  apt:
    sources:
    # Clang 7:
      - llvm-toolchain-xenial-7
      - ubuntu-toolchain-r-test
    packages:
      - abi-compliance-checker
      #- clang-7
      - doxygen
      - lzip
      - zip  
      - gcc
      - g++  
